---
title: "BiocGF: interfacing to Geneformer with R"
author: "Vincent J. Carey, stvjc at channing.harvard.edu"
date: "`r format(Sys.time(), '%B %d, %Y')`"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{BiocGF: interfacing to Geneformer with R}
  %\VignetteEncoding{UTF-8}
output:
  BiocStyle::html_document:
    highlight: pygments
    number_sections: yes
    theme: united
    toc: yes
---

# Introduction

Geneformer is described in a Nature paper
entitled [Transfer learning enables predictions
in network biology](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10949956/).
The abstract concludes: "Overall, Geneformer represents a pretrained deep learning model from which fine-tuning towards a broad range of downstream applications can be pursued to accelerate discovery of key network regulators and candidate therapeutic targets."

Software resources related to the model are available at huggingface.co.

A preprint with critical content is [Kedzierska et al.](https://www.biorxiv.org/content/10.1101/2023.10.16.561085v2).  This package collects tools
and information related to both of these papers.

# Package resources

Programming for the analyses presented in the papers
is exclusively in python.  We use [basilisk](https://bioconductor.org/packages/basilisk) to collect specified versions of all Pypi-resident dependencies.
We also include a snapshot of the Geneformer software modules
with BiocGF.

## A benchmark dataset

The Kedzierska paper includes a figshare link to a loom
file representing quantifications of single-cell RNA-seq
analyses of pancreas tissue.
