#!/usr/bin/env python
# coding: utf-8

# In[1]:


from geneformer import EmbExtractor


# In[ ]:


# initiate EmbExtractor
embex = EmbExtractor(model_type="CellClassifier",
                     num_classes=3,
                     filter_data={"cell_type":["Cardiomyocyte1","Cardiomyocyte2","Cardiomyocyte3"]},
                     max_ncells=1000,
                     emb_layer=0,
                     emb_label=["disease","cell_type"],
                     labels_to_plot=["disease"],
                     forward_batch_size=200,
                     nproc=16)

# extracts embedding from input data
# input data is tokenized rank value encodings generated by Geneformer tokenizer (see tokenizing_scRNAseq_data.ipynb)
# example dataset: https://huggingface.co/datasets/ctheodoris/Genecorpus-30M/tree/main/example_input_files/cell_classification/disease_classification/human_dcm_hcm_nf.dataset

fine_tuned_path = "/media/volume/boot-vol-vince_12apr/Geneformer/fine_tuned_models/geneformer-6L-30M_CellClassifier_cardiomyopathies_220224"
dataset_path = "/media/volume/boot-vol-vince_12apr/human_dcm_hcm_nf.dataset"
output_path = "/media/volume/boot-vol-vince_12apr/vccardio_output"

embs = embex.extract_embs(fine_tuned_path,
                          dataset_path,
                          output_path,
                          "demo_cardio")


# In[4]:


# plot UMAP of cell embeddings
# note: scanpy umap necessarily saves figs to figures directory
embex.plot_embs(embs=embs, 
                plot_style="umap",
                output_directory=output_path,
                output_prefix="emb_plot")


# In[5]:


# plot heatmap of cell embeddings
embex.plot_embs(embs=embs, 
                plot_style="heatmap",
                output_directory=output_path,
                output_prefix="emb_plot")






