

#!/usr/bin/env python
# coding: utf-8

# In[1]:

#%VC_JetS> ls -tl /media/volume/boot-vol-vince_12apr/*10dout_darm
#total 16
#drwxrwxr-x 3 exouser exouser 4096 Jul 10 14:53 240710_geneformer_cellClassifier_darmanis_test
#drwxrwxr-x 2 exouser exouser 4096 Jul 10 14:53 darmanis_test_labeled_train.dataset
#drwxrwxr-x 2 exouser exouser 4096 Jul 10 14:53 darmanis_test_labeled_test.dataset
#-rw-rw-r-- 1 exouser exouser  155 Jul 10 14:53 darmanis_test_id_class_dict.pkl


filter_list=list("cell_type"=c("Cardiomyocyte1","Cardiomyocyte2","Cardiomyocyte3"))
output_path = "/media/volume/boot-vol-vince_12apr/tryembo2"
dataset_path = "/home/exouser/newdarmtok/h5adtoks.dataset"

finepath = "/media/volume/boot-vol-vince_12apr/Geneformer/fine_tuned_models/geneformer-6L-30M_CellClassifier_cardiomyopathies_220224"
dataset_path = "/media/volume/boot-vol-vince_12apr/human_dcm_hcm_nf.dataset"
output_path = "/media/volume/boot-vol-vince_12apr/vjccardiooutputjul14"



library(BiocGF)

get_gf_emb_cellcl = function(finepath, 
   dataset_path, output_path, tag = "demoextor", filter_list, max_ncells = 1000L,
   emb_layer = 0L, emb_labels = c("disease", "cell_type"), 
   labels_to_plot = "disease", forward_batch_size = 100L, nproc = 16L) {

 proc = basilisk::basiliskStart(BiocGF:::gfenv)
 on.exit(basilisk::basiliskStop(proc))
 basilisk::basiliskRun(proc, function(finepath, dataset_path, output_path,
       filter_list, max_ncells, emb_layer, emb_labels,
       labels_to_plot, forward_batch_size, nproc) {
    gfbase = reticulate::import_from_path("geneformer",
      path=system.file("python", "Geneformer", package="BiocGF"))
    l2rd = function(lis) reticulate::dict(lis)
    filter_dict = l2rd(filter_list)
    extor = gfbase$EmbExtractor(
      model_type = "CellClassifier",
      num_classes = as.integer(length(filter_list[[1]])), # FIXME!  is 1 right?
      filter_data = filter_dict,
      max_ncells = max_ncells, forward_batch_size=forward_batch_size,
      nproc = nproc)
    print(names(extor))
    emb = extor$extract_embs(finepath,
                          dataset_path,
                          output_path, tag)
    ds = reticulate::import("datasets")
    dsref = ds$load_from_disk(dataset_path)
    sampvals = lapply(emb_labels, function(x) dsref[[x]][seq_len(max_ncells)])
    names(sampvals) = emb_labels
    list(emb=data.matrix(emb), samplabs = sampvals)

    }, finepath, dataset_path, output_path,
       filter_list, max_ncells, emb_layer, emb_labels,
       labels_to_plot, forward_batch_size, nproc)
   }

lkemb_hf = get_gf_emb_cellcl( finepath=finepath, dataset_path=dataset_path,  max_ncells=100000L,
   output_path=output_path,
   filter_list=filter_list)

save(lkemb_hf, file="lkemb_hf.rda")


      
# extracts embedding from input data
# input data is tokenized rank value encodings generated by Geneformer tokenizer (see tokenizing_scRNAseq_data.ipynb)
# example dataset: https://huggingface.co/datasets/ctheodoris/Genecorpus-30M/tree/main/example_input_files/cell_classification/disease_classification/human_dcm_hcm_nf.dataset


#>>> ds.load_from_disk(("h5adtoks.dataset")
#... 
#... )
#Dataset({
#    features: ['input_ids', 'batch', 'donor', 'n_counts', 'age', 'cell.type', 'tissue', 'chipid', 'length'],
#    num_rows: 466
#})
#>>> 
#%VC_JetS> pwd
#/home/exouser/newdarmtok


#fine_tuned_path = finepath
##dataset_path = "/media/volume/boot-vol-vince_12apr/vjcjul10dout_darm/darmanis_test_labeled_train.dataset"
#output_path = "/media/volume/boot-vol-vince_12apr/tryembo"
#dataset_path = "/home/exouser/newdarmtok/h5adtoks.dataset"
#
#embs = embex.extract_embs(fine_tuned_path,
#                          dataset_path,
#                          output_path,
#                          "demo_darm")

#
## In[4]:
#
#
## plot UMAP of cell embeddings
## note: scanpy umap necessarily saves figs to figures directory
#embex.plot_embs(embs=embs, 
#                plot_style="umap",
#                output_directory=output_path,
#                output_prefix="emb_plot")
#
#
## In[5]:
#
#
## plot heatmap of cell embeddings
#embex.plot_embs(embs=embs, 
#                plot_style="heatmap",
#                output_directory=output_path,
#                output_prefix="emb_plot")
#
#
#
#
#
#
